server {
    listen 80;
    server_name localhost;

    # フロントエンド（React）の静的ファイル配信
    location / {
        root /usr/share/nginx/html;# ファイルのあるルートディレクトを指定
        index index.html index.htm;# ファイル名未指定時に返すデフォルトファイルの指定
        try_files $uri $uri/ /index.html;# 実ファイル、フォルダを探し、なければ/index.htmlを返す
    }

    # バックエンドへのリバースプロキシ転送
    location /api/ {
        proxy_pass http://backend:3000;           # 転送先の指定
        proxy_http_version 1.1;                   # HTTP/1.1指定でKeep-Aliveを有効化（通信の高速・安定化）
        proxy_set_header Host $host;              # クライアントがアクセスした元のドメインを引き継ぐ
        proxy_set_header X-Real-IP $remote_addr;  # 直前のアクセス元IPアドレスを引き継ぐ
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;# 経由した全プロキシ・送信元IPの経路履歴を引き継ぐ
        proxy_set_header X-Forwarded-Proto $scheme;# 通信プロトコル（http/https）を引き継ぐ
    }
}